Repository ietf-wg-aipref/drafts, pull requests merged in 2025-09, with the labels that each got.

#131 Tweak 3.2
  draft-ietf-aipref-vocab.md
Labels: vocabulary, editorial

#124 Extraneous phrase
  draft-ietf-aipref-vocab.md
Labels: vocabulary, editorial

#135 Clean up HTTP example
  draft-ietf-aipref-attach.md
Labels: location attachment, editorial

#137 Move from "expression" to "statement"
  draft-ietf-aipref-attach.md
  draft-ietf-aipref-vocab.md
Labels: editorial

#143 Lowercase only people
  draft-ietf-aipref-vocab.md
Labels: editorial

#145 More clarity about vocabulary extensions
  draft-ietf-aipref-vocab.md
Labels: editorial

#142 Parameters carry through
  draft-ietf-aipref-vocab.md
Labels: editorial

#144 Restructure "other mechanisms" section
  draft-ietf-aipref-attach.md
Labels: editorial
